build:
  image: docker:latest
  stage: build
  allow_failure: false
  variables:
    PLATFORMS: "linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6"
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - apk add --no-cache docker-cli-buildx
    - docker buildx create --name BuildX --use
  script:
    - echo Building for platforms ${PLATFORMS}
    - docker buildx build
      --platform "${PLATFORMS}"
      --compress --push
      -t ${CI_REGISTRY_IMAGE} .
  only:
    - main
