build:
  image: docker:latest
  stage: build
  allow_failure: false
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - apk add --no-cache docker-cli-buildx
    - docker buildx create --name BuildX --use
  script:
    - PLATFORMS=`docker buildx inspect --bootstrap | grep Platforms | cut -d ' ' -f 1 --complement`
    - echo Building for platforms ${PLATFORMS}
    - docker buildx build
      --platform "${PLATFORMS}"
      --compress --push
      -t ${CI_REGISTRY_IMAGE} .
  only:
    - main
