version: "3.8"

services:
  DockerEvents:
    image: registry.gitlab.com/ighor/dockerevents:latest
    container_name: DockerEvents
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/hostname:/etc/hostname:ro
    environment:
      TELEGRAM_API_TOKEN:
      TELEGRAM_GROUP_ID:
      TELEGRAM_MENTION:
      TIMEZONE:
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "0.1"
          memory: '50M'
